### ISSUE TITLE
Component does not query/load any suggestions

### ISSUE THREAD

**Issue by negati-ve** [Tintef/react-google-places-autocomplete#162] opened 2021-03-11 12:58 UTC
Node version: 15.11.0
tested on Mac OS 11.1 and Alpine 3.10
no errors in console 

suggestions  don't load after user inputs text in field. (no network requests are  fired)
![image](https://user-images.githubusercontent.com/13253073/110790389-fd38de80-8296-11eb-9e1b-bc990fc35959.png)

Current solution:
Downgrading react-google-places-autocomplete to v3.1.1 fixes the issue

will report more on the issue as I find more info

**Comment by Tintef** [comment] 2021-03-11 16:12
@negati-ve Can you share some of your code?

**Comment by negati-ve** [comment] 2021-03-12 05:21
sure
```

import React, { useState } from 'react';
import GooglePlacesAutocomplete, { geocodeByAddress, getLatLng } from 'react-google-places-autocomplete';

const GetDeliveryAddress = ({ Store }) => {
    const [value, setValue] = useState({ label: Store.address, value: { description: Store.address } });
    const setValueChange = (x) => {
        setValue(x);
        geocodeByAddress(x.label)
            .then(results => getLatLng(results[0]))
            .then(({ lat, lng }) => {
                Store.setAddress(x.label);
                Store.setCoordinates({ lat, lng });
            }
            );
    };
    return <React.Fragment>
        <GooglePlacesAutocomplete
            apiKey={process.env.NEXT_GOOGLE_MAPS_API_KEY}
            autocompletionRequest={{
                componentRestrictions: {
                    country: ['in'],
                }
            }}
            selectProps={{
                value,
                onChange: setValueChange,
                placeholder: 'Enter building or street address',
            }}
        />
    </React.Fragment>;
};

export default GetDeliveryAddress;
```

Working smooth on v3.1.1
upgrading to v3.2.3 breaks the suggestion box

**Comment by DorskFR** [comment] 2021-03-12 23:31
same issue here, I noticed the dropdown had a seamingly low zIndex because it becomes hidden behind other components making the selection of items difficult.

I saw the update and upgraded just in case it would fix that but I get the same as above, no suggestions anymore.

**Comment by Tintef** [comment] 2021-03-13 00:49
@negati-ve @DorskFR This is working for me on both a codesanbox and a fresh next project.

Can both of you verify that if the script is being included or not in the `head` of your document?

**Comment by negati-ve** [comment] 2021-03-13 12:24
script is being loaded 100%

included the script manually and tried as well (which showed a console warning that "Google Maps already loaded outside @googlemaps/js-api-loader.This may result in undesirable behavior as options and script parameters may not match.".. indicating js api loader was infact registered)

**Comment by DorskFR** [comment] 2021-03-13 12:34
The script is loaded.
When typing in the field, it does display "loading..." for a split second then No options.

Works with 3.2.2 breaks with 3.2.3 for me.

I am using it like this

```
<Grid
        item
        className={classes.orderConfirmGridAddress}
      >
        <IconButton onClick={() => setAddAddress(false)} style={{ display: 'inline' }}>
          <ImportContactsIcon
            className={classes.inputIcon} />
        </IconButton>
        <GooglePlacesAutocomplete
          selectProps={{
            googleAddress,
            onChange: setGoogleAddress,
            components: {
              Menu,
            },
            menuPortalTarget: document.body,
            styles: {
              container: (provided) => ({
                ...provided,
                width: '100%',
              }),
              input: (provided) => ({
                ...provided,
                fontSize: 'clamp(0.75rem, 2vw, 1rem)',
                fontWeight: 600,
                width: '100%',
                minWidth: '100%',
                display: 'inline',
                margin: 0,
                lineHeight: '46px',
                minHeight: '50px',
                zIndex: 1000,
              })
            },
          }}
          apiOptions={{ language: 'it', region: 'it' }}
          autocompletionRequest={{
            componentRestrictions: {
              country: ['it'],
            },
            types: ["address"]
          }}
        />
```

**Comment by Tintef** [comment] 2021-03-13 14:23
For @DorskFR I think the issue is that the `apiKey` prop is not being used and that makes the service not be initialized. This is a bug and I'll fix it asap.

For @negati-ve I'm still not sure what's happening, as I was able to make it working using next. Is your `apiKey` for the `places` API?

**Comment by Tintef** [comment] 2021-03-13 14:29
@DorskFR Please verify that your issue gets fixed with v3.2.4

Leaving the issue open until we find out what's happening to @negati-ve

**Comment by negati-ve** [comment] 2021-03-14 07:10
v3.2.4 fixes the issue 🎉🥳

**Comment by Tintef** [comment] 2021-03-14 14:13
Awesome! I'll close the issue then 🤗

**Closed by Tintef** 2021-03-14 14:13 UTC

**Comment by Resource-3** [comment] 2022-02-14 06:47
Seeing this issue again when using with @react-google-maps/api
