### ISSUE TITLE
Location and Bounds do not work as specified in documentation

### ISSUE THREAD

**Issue by dextercallender** [Tintef/react-google-places-autocomplete#11] opened 2019-07-16 16:52 UTC
According to the documentation, the following request constraints should work.

`const autocompletionRequest = {
            componentRestrictions: { country: 'us' },
            location: { lat: Number(40.7128),  lng: Number(74.0060) },
            radius: 5
}`

I am receiving the error: 'Uncaught (in promise) TypeError: a.lat is not a function' back from Google places API. I believe the code processing the location and creating the google.maps.LatLng object may have an issue. I was experiencing the same issue while creating bounds.

**Comment by Tintef** [comment] 2019-07-16 19:57
I’ll take a look at this tomorrow, thanks for reporting!

**Comment by AxelAli** [comment] 2019-07-16 20:29
Hi there, i was just stepping over this .
For some reason you are not passing the **_autocompletitionRequest_** props to the **_getPlacePredicitons_**
My solution is 
`Object.assign(_this.props.autocompletionRequest,{input: value}))`
Line 102 @ react-places-autocomplete/dist/PlacesAutocomplete.js

**Comment by Tintef** [comment] 2019-07-16 21:18
Hey @AxelAli thanks for taking a stepping over!

I would prefer to figure out why the spread operator is not working before using `Object.assing(...`

**Comment by Tintef** [comment] 2019-07-16 21:54
@AxelAli

As far as I was able to debug this, it looks like what you are mentioning is not the problem. Actually what's happening is that the `location` is not a `LatLng`.

So, making this:
```
let location = undefined;
if (autocompletionRequest.location) {
 location = new google.maps.LatLng(autocompletionRequest.location);
}
```

And sending that location on the ` this.placesService.getPlacePredictions` call doesn't throws the error @dextercallender reported.

Now I'm checking this works as expected (the restrictions are correctly applied) before making a PR to close this issue.

**Comment by Tintef** [comment] 2019-07-16 22:09
@AxelAli @dextercallender 

This fix works 🎉 I'll merge and update the package so you can give it try!

Let me know if this doesn't work for any of you guys.

Note: @dextercallender your lat/lng coordinates are for somewhere in China (just so you know)

**Closed** 2019-07-16 22:25 UTC

**Comment by dextercallender** [comment] 2019-07-25 21:21
Thanks for the quick reply but I'm still having some issues with the suggested solution...

Can you provide an example of what it the autocompletionRequest object would look like for a 10 mi. radius around NYC for example?

**Comment by AxelAli** [comment] 2019-07-25 21:29
Hi there. 

i would suggest you take a look at [this](https://developers.google.com/maps/documentation/javascript/reference/places-service#TextSearchRequest) probably  bounds or radius

**Comment by Tintef** [comment] 2019-07-25 21:31
Thanks for stepping over again @AxelAli 

Also @dextercallender, it's always helpful to see your code, so we know what are you doing. A codepen or similar to reproduce what you are doing would be awesome too
