### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended

### ISSUE THREAD

**Issue by Hassan-Zahid** [Tintef/react-google-places-autocomplete#70] opened 2020-05-19 09:07 UTC
Easily recreatable when accessed in `<React.StrictMode>`. Any suggestions or recommendations for this one would be highly appreciated.

<img width="1680" alt="Screenshot 2020-05-19 at 1 54 24 PM" src="https://user-images.githubusercontent.com/5285786/82307561-f5dbd800-99d9-11ea-8d0f-35cc8b16f5ba.png">

**Comment by Tintef** [comment] 2020-05-19 19:54
@Hassan-Zahid I'm not sure if there's something for you to do on your side, the library needs an update to stop using that and move to `componentDidUpdate`.

I'm not sure when I'll be able to take a look a this, but PRs are welcomed!

**Comment by Tintef** [comment] 2020-08-24 03:16
@Hassan-Zahid  FYI, this is already released as an alpha version, you can install it with:

```yarn add react-google-places-autocomplete@3.0.0-alpha.0```

And you can find the new docs [here](https://tintef.github.io/react-google-places-autocomplete/)

**Comment by Tintef** [comment] 2020-08-28 11:37
@Hassan-Zahid This is already merged in master (but still an alpha release)

**Closed by Tintef** 2020-08-28 11:38 UTC
Labels: good first issue

**Comment by KBeDevel** [comment] 2021-02-17 16:51
I'm seeing this warning and I'm using react-google-places-autocomplete@3.1.1 :/

**Comment by Tintef** [comment] 2021-02-21 21:05
@KBeDevel Can you provide a minimal reproducible repo? I'm not getting this since 3.0.0 was release

**Comment by KBeDevel** [comment] 2021-02-24 21:11
Well, after some checks, I figured out that I'm not getting **EXACTLY** the same error.

I just created an instance of `GooglePlacesAutocomplete` component inside a `Form` (react-bootstrap) component:

```tsx
<GooglePlacesAutocomplete
  apiKey={ ProvidersHelper.keys.google.places.autocomplete }
  autocompletionRequest={{
    componentRestrictions: {
      country: this.state.country?.toLocaleLowerCase() ?? ''
    }
  }}
  onLoadFailed={ (error) => { console.error(error) } }
  minLengthAutocomplete={ 3 }
  selectProps={{
    onChange: (value) => { this.updateAddress(value) },
    isDisabled: !this.state.country, // ISO 3166-2 in UPPERCASE or an empty string
    placeholder: this.state.country ? 'Please type an address' : 'Please select a country to start searching',
    components: {
      Menu: showPoweredByGoogleHelper,
      LoadingIndicator: loadingIndicatorPatch,
    },
    className: 'search-address-box',
    inputId: 'finishSignUpAddressSearch',
    menuPortalTarget: document.body,
    styles: {
      ...defaultSelectStyles, // Not really important to include
      menuPortal: (styles) => ({
        ...styles,
        zIndex: 12
      }),
      indicatorSeparator: (styles) => ({
        ...styles,
        display: 'none'
      }),
      dropdownIndicator: (styles) => ({
        ...styles,
        display: 'none'
      }),
      indicatorsContainer: (styles, { isDisabled, hasValue }) => ({
        ...styles,
        display: (isDisabled || hasValue) ? 'none' : 'flex',
        color: '#ced4da',
        marginRight: '.5rem'
      }),
    }
  }} />
```

When I render the page (with Firefox, Chromium and Brave), I'm getting this warning:

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: i, n, r index.js:1
    e index.js:1
    React 5
        printWarning
        error
        flushPendingUnsafeLifecycleWarnings
        flushRenderPhaseStrictModeWarningsInDEV
        commitRootImpl
    unstable_runWithPriority scheduler.development.js:646
    React 9
        runWithPriority$1
        commitRoot
        performSyncWorkOnRoot
        scheduleUpdateOnFiber
        updateContainer
        legacyRenderSubtreeIntoContainer
        unbatchedUpdates
        legacyRenderSubtreeIntoContainer
        render
    tsx index.tsx:20
    tsx main.chunk.js:8967
    Webpack 7
        __webpack_require__
        fn
        1
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
```

And when I click on the control (without any additional event) I'm getting these two:

- Warning 1
  ```
  Warning: Legacy context API has been detected within a strict-mode tree.

  The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

  Please update the following components: t
  ```

- Warning 2:
  ```
  Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of o which is inside StrictMode. Instead, add a ref directly to the element you want to reference
  ```

I'm getting and using the autocomplete result set without any problem. This is not a functional issue is just an unexpected stack of warnings

Related packages:

- "react-google-places-autocomplete": "^3.2.1",
- "react": "^17.0.1",
- "react-bootstrap": "^1.5.0",
- "react-dom": "^17.0.1",
- "react-select": "^4.1.0", (I'm using the `Select` components too without any problems)
- "typescript": "^4.1.5",

---

*Note:  I'm not totally sure if this requires a new issue*

**Comment by Tintef** [comment] 2021-02-26 20:22
@KBeDevel Can you provide a repository where this can be reproduced?

If so I can take a look :)

**Comment by KBeDevel** [comment] 2021-03-08 12:39
Sorry for the late response. These warnings are not longer appearing in the 3.2.2 version.

PD: Nice work with this project!
