### ISSUE TITLE
use UNSAFE_componentWillReceiveProps instead of componentWillReceiveProps

### ISSUE THREAD

**Issue by theweiweiway** [Tintef/react-google-places-autocomplete#40] opened 2020-01-12 21:25 UTC
componentWillReceiveProps will be deprecated in React 17.0, and must be renamed to UNSAFE_componentWillReceiveProps.

I tried to make a pull request but couldn't figure out how :( (im noob). It's a quick change, just change line 57 to UNSAFE_componentWillReceiveProps

**Comment by Tintef** [comment] 2020-01-12 23:12
@theweiweiway Hey, thanks!

To make a PR you need to:

1. Fork the repo
2. Make your changes and create a new commit
3. Open a PR from your fork to the main repo (this one)

I'm more than glad to review + approve a PR 😄

**Comment by Tintef** [comment] 2020-01-13 22:33
Also, duplicate of #32 , closing this one. If you want to make a PR please do so to close #32

**Closed by Tintef** 2020-01-13 22:33 UTC
