### ISSUE TITLE
Support for defaultProps error.

### ISSUE THREAD

**Issue by Somacros** [Tintef/react-google-places-autocomplete#347] opened 2024-03-21 02:10 UTC
Hello there!
I'm starting to use this library and just encounter this next error:
<img width="529" alt="image" src="https://github.com/Tintef/react-google-places-autocomplete/assets/57009512/65a87de0-ca4e-46a8-9e0e-58336003a951">

So I have been searching a little bit but can't find any solutions for this library in particular, just a pull request from someone else that has been up since December 2023.

Is there any solution or is the team working on it? I want to know as it might be a future problem that I would love to avoid from impacting production x_x.

Thank you for the hard work guys!

**Comment by PalomoLH** [comment] 2024-05-12 00:58
Same problem here, i think the author is not updating anything now, but i`ll fork the repo and fix in here, i think is the best for now approach

**Comment by Tintef** [comment] 2024-08-26 01:15
Duplicate of https://github.com/Tintef/react-google-places-autocomplete/issues/350. Closing.

**Closed by Tintef** 2024-08-26 01:15 UTC
