### ISSUE TITLE
Handling pressing Enter in a `renderInput` component - like form submission

### ISSUE THREAD

**Issue by alanbuchanan** [Tintef/react-google-places-autocomplete#65] opened 2020-04-19 22:29 UTC
Thank you for the excellent library.

I want to be able to run a function when the user hits the Enter key while searching for something.

However, according to the documentation:
> Important: do not override the value and onChange properties of the input, neither the onBlur or onKeyDown.

I am referring to the `renderInput` prop of the `GooglePlacesAutocomplete` component.

To get around this I tried placing the input field inside a `<form>` with an `onSubmit` prop but that didn't fire.

So I went against the documentation and wrote an `onKeyDown` handler which check if the `event`'s `keyCode` is 13 (Enter).

This seemed to work perfectly fine. However as I went against the documentation I fear this might break some key functionality somewhere.

Is it safe to target the Enter key in an `onKeyDown` handler? Or should I approach this in a different way?

**Comment by Tintef** [comment] 2020-04-20 20:59
Hi @alanbuchanan, really glad that you like the library 😄 

You're not supposed to override the `onKeyDown` because that handles the arrows navigation inside the suggestions menu and the ability to press `Enter` to select from the menu!

If you really need to override it, you can (and should) do something like this:

```
<GooglePlacesAutocomplete
  apiKey="*********"
  onSelect={console.log}
  renderInput={(props) => (
    <input
      {...props}
      onKeyDown={(ev) => {
        props.onKeyDown(ev);

        if (ev.key === 'Enter') {
          console.log('Hi @alanbuchanan');
        }
      }}
	/>
  )}
/>
```

Hope it helps!

**Comment by Tintef** [comment] 2020-04-22 21:21
@alanbuchanan Closing this one as it's pretty simliar as #67 and OP there confirmed that it worked.

Let me know if you have any more doubts/concern!

**Closed by Tintef** 2020-04-22 21:21 UTC
