### ISSUE TITLE
Get data from input

### ISSUE THREAD

**Issue by maximiliano-gt** [Tintef/react-google-places-autocomplete#121] opened 2020-09-15 12:38 UTC
How can i get the result selected by the user? 

im doing this but is not working: 

```
        <GooglePlacesAutocomplete
               onSelect={ data => {
                console.log(data)
              }}
```

**Comment by Tintef** [comment] 2020-09-15 14:59
@maximiliano-gt My recommendation is to use the select as a [controlled input](https://tintef.github.io/react-google-places-autocomplete/docs/examples#controlled-input).

**Comment by bryantee** [comment] 2020-09-16 20:58
I very much am interested in implementing as a controlled component but the basic example is not working for me.

```tsx
const [value, setValue] = useState(null);

<GooglePlacesAutocomplete
  selectProps={{
    value,
    onChange: setValue,
  }}
/>
```

`onChange` never appears to be getting called, even after a selection is made. And so `value` is never updated. 🤔

**Comment by Tintef** [comment] 2020-09-16 21:11
@bryantee Can you send some more code or a reproducible repo/codesanbox?

I was able to see it working with this:
```
import React, { useEffect, useState } from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";
import "./styles.css";

export default function App() {
  const [value, setValue] = useState(null);

  useEffect(() => {
    console.log("value: ", value);
  }, [value]);

  return (
    <div className="App">
      <GooglePlacesAutocomplete
        apiKey="<YOUR_API_KEY>"
        selectProps={{
          value,
          onChange: setValue
        }}
      />
    </div>
  );
}

```

**Comment by codepurse** [comment] 2020-09-17 03:25
Hmm. I dont know if I need to open a another issue. But Ill post it instead because its kinda similar i guess.

I cannot change the value when Im trying to change the state. 

`import React, { useEffect, useState } from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";
import "./styles.css";

export default function App() {
  const [value, setValue] = useState(null);
  const [address, setAddress] = React.useState("");

  useEffect(() => {
    console.log("value: ", value);
  }, [value]);

  return (
    <div className="App">
      <GooglePlacesAutocomplete
        apiKey="<YOUR_API_KEY>"
        selectProps={{
          value: address,
        }}
      />
    </div>
  <button onClick={() => setAddress("Example Text")} >set</button>
  );
}`

But if I tried in other object like textbox or paragraph its works. Thanks in advance! <3

**Comment by Tintef** [comment] 2020-09-17 12:31
@codepurse Please read (react-select StateManager prop)[https://react-select.com/props#statemanager-props].

If you want to use `value` you need to provide `One of<Object, Array<Object>, null, undefined>`.

For strings, you should use `inputValue` instead.

**Comment by Tintef** [comment] 2020-09-19 19:39
Closing this one as it seems everything has been solved.

**Closed by Tintef** 2020-09-19 19:39 UTC

**Comment by bryantee** [comment] 2020-09-20 16:31
Sorry @Tintef saw your comment and hadn't had a chance to go back and investigate. Dropped back to v2.x as we had in our existing project in the meantime.

If I have anytime over the next week to get back into it I'll be sure to post back here.
